ACCESS-NRI/spack-packages

packages/access-om3/package.py
Currently implemented as a bundle, as for now we only want the dependencies.
I've pinned the versions, as I want them to be the same as the ones we are using on Gadi, but at some point this condition should be relaxed.
=> Add ACCESS-OM3 package

packages/nci-openmpi/package.py
Add a package for NCI's particular way of installing OpenMPI so that Cmake builds pick up libraries correctly
Sets `OMPI_FCFLAGS` and `OMPI_LDFLAGS` appropriately depending on the compiler in use.
=> Add nci-openmpi

.github/workflows/dispatch-update-to-build-ci.yml
GitHub Actions can be strange. In order for build-ci to know that spack_packages has been updated, spack_packages needs to notify build-ci that there has been a change. In this PR, workflows are added to notify build-ci that spack_packages has had a push to master, or a tag released. 
Related PR from build-ci: https://github.com/ACCESS-NRI/build-ci/pull/19
Should go partway to closing ACCESS-NRI/build-ci#4 !
=> Workflow For Notifying ACCESS-NRI/build-ci that spack_packages is Updated

packages/access-om2/package.py, packages/cice5/package.py, packages/libaccessom2/package.py, packages/mom5/package.py, packages/oasis3-mct/package.py
* This PR is only focused on adding the deterministic variant.
* The general compiler flag audit will happen in https://github.com/ACCESS-NRI/ACCESS-OM/issues/12
* We'll likely end-up storing the compiler flags in an appropriate data structure and then extract the relevant compiler flags based on the variant/compiler.
=> Add a deterministic variant

.github/workflows/dispatch-update-to-build-ci.yml
Since all of the packages will be part of the same image, there will be no need to conditionally compile some of them. We'll just use the regular workflow that compiles all of them. 
Should go partway to closing https://github.com/ACCESS-NRI/build-ci/issues/9 !
=> CI refers to the build-and-push-image-build.yml workflow

.github/workflows/dispatch-update-to-build-ci.yml
The changes to `build-ci` removed the `spack-packages-build-required` input parameter, but this wasn't removed from spack_packages. This PR removes it.
=> Updated input parameters to fit with `build-ci` inputs

packages/libaccessom2/package.py
Modify CMakeLists.txt directly from the SPD instead of having a two step process, where we have to add the variant to the SPD and then go modify the package's source code repository.
=> libaccessom2: allow variants to directly modify CMakeLists.txt

packages/issm/package.py, packages/m1qn3/m1qn3.patch, packages/m1qn3/package.py, packages/nci-intel-oneapi-mkl/package.py
As mentioned in #20, here is the ISSM package which pulls in PETSc and builds using Intel compilers and MKL on Gadi. The `packages.yaml` may need to be modified for site configurations to specify that `intel-oneapi-mkl` uses the `+cluster` variant in order to include ScaLAPACK and BLACS.
It's also possible that `intel-oneapi-mkl` can be renamed to something more NCI-specific, like the existing `nci-openmpi` package.
=> Add the ISSM model and supporting packages

.github/workflows/py-checks.yml
In this PR:
* `actions/checkout` now checks out the repository specified by the `pull_request` webhook payload (`${{github.event.pull_request.head.repo.full_name}}`) which can be a forked repo!
* Uses more stable `tj-actions/changed-files` reusable workflow
* Added a newline to the end of the file
Closes #45 !
=> Updated repo checkout rules to allow linting checks with forked repository PR

.github/workflows/py-checks.yml, .ruff.toml
The '--format' argument is tripping up the pipeline, even though it is a valid argument in `ruff help check`. 
It isn't required for the workflow to run (mostly just pretty-printing), so it has been removed. Adding it to the `.ruff.toml` seems valid.
=> Removed unneeded '--format' argument

packages/mom5/package.py
The MOM5 commit d7ba13a3f364ce130b6ad0ba813f01832cada7a2 requires the --no_version switch to avoid git hashes being embedded in the binary.
=> mom5: new switch --no_version is required

packages/access-om2/package.py
In this PR, we remove the hardcoded `version("2023.0.001-1")` and add in the git repo, so we can associate a particular build of access-om2 with a git commit (aka, so we can have a `spack install access-om2@git.2023.11.20` for example).
=> access-om2: Added link to git repo, removed hardcoded version string

packages/mom5/package.py
The cice5 SPD already does this. This code was in the same `development` commit as mom5's `netcdf-c~mpi` dependency testing code and did not reach `main`
=> mom5: print the generated config file to stdout.

packages/nci-openmpi/package.py
* Use env.append_flags() instead of env.append_path().
* Thanks to Aidan Heerdegen for finding env.append_flags().
=> nci-openmpi: use env.append_flags()

packages/nci-openmpi/package.py
* Spack is planning on removing the implicit import of spack.package. See https://github.com/spack/spack/pull/39380
* Recommended changes from the code review have been add. See https://github.com/ACCESS-NRI/spack-packages/pull/21
=> nci-openmpi: do not rely on implicit import of spack.package

packages/libaccessom2/package.py
Details can be found in https://github.com/ACCESS-NRI/spack-packages/issues/61 .
=> libaccessom2: explicitly set CMake compiler variables

packages/mom5/package.py
* "type" will have options ACCESS-CM, ACCESS-OM, ACCESS-ESM, ACCESS-OM-BGC and MOM_solo.
=> mom5: add new variant "type"

packages/cable/package.py
This change adds a spack package for [CABLE](https://github.com/CABLE-LSM/CABLE) (offline configuration).
This change should follow after a CMake based build system has been implemented, see: https://github.com/CABLE-LSM/CABLE/pull/200, https://github.com/CABLE-LSM/CABLE/pull/216.
Package installation tested with:
spack install cable@git.215-additional-cmake-changes +mpi %intel@19.0.5.281 ^netcdf-fortran@4.6.0 ^nci-openmpi@4.0.2
Fixes #58
=> Add CABLE spack package

packages/cable/package.py
Currently the CABLE spack build leaves the `CABLE_MPI` CMake variable unset when `~mpi` is satisfied and relies on the default value for `CABLE_MPI`. This change removes the if condition around `define_from_variant` so that `CABLE_MPI` is specified to CMake regardless of how the mpi variant is set.
Fixes #76
=> Fix mpi logic in CABLE SPD

packages/mom5/package.py
We need a reproducibility variant for `mom5` for repro CI testing
See https://github.com/ACCESS-NRI/access-om2-configs/issues/11 for context.
=> Added +restart_repro variant

packages/access-om2/package.py
Add +restart_repro variant to access-om2 (default true)
As the variant only needs to be propagated to `mom5` it doesn't add a heap of ugly combinatorial boilerplate.
Closes #78
=> Add restart_repro variant to access-om2 (default true)

.ruff.toml, packages/access-om2-bgc/package.py
In this PR:
﻿
* Added access-om2-bgc package definition, inheriting from AccessOm2 package
* .ruff.toml: Removed check on line length as part of #73
Closes #80
Closes #73
=> Add `ACCESS-OM2-BGC` Package

packages/gcom4/package.py
Closes Issue #68 . See that issue for a description of the change requested.
This package applies patches to files in https://github.com/ACCESS-NRI/GCOM/tree/dev/Share/gcom4.5_access_config
as per https://github.com/coecms/access-esm-build-gadi/blob/master/Makefile rather than relying on updating the upstream repository.
The package has been tested to the point where the install completes.
=> Add gcom4 package

packages/dummygrib/package.py
The repository at https://github.com/coecms/dummygrib includes a `Makfile` without an `install` target. The package for `dummygrib` is based on `MakefilePackage` with an added `install` member function. Tested the package, and the library builds and installs with both `gcc-8.5.0` and `intel-19.0.5.281` compilers.
=> Initial package for dummygrib

packages/access-om3/package.py
In this PR:
* access-om3: Added correct depends_on argument - was the old `access-om3-cmake`. Whoops.
=> Changed `depends_on` call to actual package name

packages/access-om3-nuopc/package.py
@aidanheerdegen had found that there are packages in the `spack.builtins` that use a top-level `submodules = True` attribute that forces cloning of submodules for all versions, not just the ones that are in `version(..., submodules = True)`. This isn't found in the documentation, but it has been quite difficult trawling through the documentation, anyway. 
This is especially helpful for checking out versions properly in the `@git.` syntax, which aren't necessarily going to all be enumerated by `version(...)` methods. 
A similar way to do this in `spack.yaml` would be to add it to the `spack.packages.*.package_attributes` field, like so:
```yaml
spack:
packages:
access-om3-nuopc:
package_attributes:
submodules: True
```
See more in …
=> Added `submodule` attribute to `access-om3-nuopc`

packages/um7/package.py
Closes issue #70. This is an initial Spack package for UM vn7.3, as a dependency of ACCESS-ESM1.5. See also issue #59. 
Builds and installs as `um7%intel`. There is also an optional `um7%oneapi` but this has not yet been tested, and is not expected to work at the moment. See [this comment to issue #59](https://github.com/ACCESS-NRI/spack-packages/issues/59#issuecomment-2021930280) for a possible extension to support `gcc` compilers.
=> Spack package for UM vn7.3

packages/dummygrib/package.py
Closes #88
Change the `dummygrib` package so that it uses the [ACCESS-NRI/dummygrib](https://github.com/ACCESS-NRI/dummygrib) repository. The package builds and also the `um7` package builds using the built `dummygrib` library.
=> Use ACCESS-NRI/dummygrib

packages/access-om3-nuopc/package.py
See https://github.com/ACCESS-NRI/ACCESS-OM3/pull/5#issuecomment-2089614861 and `spack.yaml` in https://github.com/ACCESS-NRI/ACCESS-OM3/pull/5/files#diff-e8582e74fa156f4e5729a850e52b24f2fde2d815c2c9c360f88c4cf90db851ab
In this PR:
* Propagate `build_type==RelWithDebInfo` down the relevant dependencies in `access-om3-nuopc`
* Move compiler flags into the `depends_on` functions (if they are `intel` compilers)
* Removed `+deprecated_io` variant
* Removed `+install_libraries`, instead using the default `~install_libraries`
Closes #102
=> Move variants/compiler flags from `spack.yaml` to relevant `package.py`s

packages/cice4/package.py, packages/cice5/package.py, packages/mom5/package.py, packages/oasis3-mct/package.py
[Updated 06/05/2024]
This PR is the first step to addressing Issue https://github.com/ACCESS-NRI/spack-packages/issues/52
Fixes: `==> Error: KeyError: 'oneapi'`
=> Add support for the Intel ifx compiler

packages/access-esm1p5/package.py
Initial SPD for ACCESS-ESM1.5. Building MOM5 and UM7 is disabled for the moment.
=> access-esm1p5: create SBD

packages/cice4/package.py, packages/mom5/package.py
Closes #104 
The build of
```
spack install mom5@access-esm1.5%intel@19.0.5.281 arch=linux-rocky8-x86_64
```
completes successfully, and running https://github.com/ACCESS-NRI/access-esm1.5-configs/tree/pre-industrial with appropriate changes to executable locations
```
$ grep "    exe:" config.yaml
exe: /g/data/tm70/pcl851/src/ACCESS-NRI/release/linux-rocky8-x86_64/intel-19.0.5.281/um7-7.3-tn5nef76eygrvbstm3ionmid6hysrij2/bin/um_hg3.exe
exe: /g/data/tm70/pcl851/src/ACCESS-NRI/release/linux-rocky8-x86_64/intel-19.0.5.281/mom5-access-esm1.5-qgaq7scgvrlvm77yvqrhllzbl7657pzl/bin/fms_ACCESS-CM.x
exe: /g/data/tm70/pcl851/src/ACCESS-NRI/release/linux-rocky8-x86_64/intel-19.0.5.281/cice4-access-esm1.5-ktkbqdnat4etwrh6v3zavmricogmin5e/bin/cice_access_360x300_12x1_12p.exe
```
also completes, but …
=> Add an ACCESS-ESM1.5 version

packages/gcom4/package.py, packages/um7/package.py
Closes #112. The `um7` executable builds. The output of the `pre-industrial` configuration does not reproduce bitwise, but this can be addressed by separate issues, such as #113 .
=> Use the access-esm1.5 version and branch of GCOM4

packages/mom5/package.py
Closes #112 
I tested with three different variants:
```
$ spack find -v mom5
-- linux-rocky8-x86_64 / intel@19.0.5.281 -----------------------
mom5@access-esm1.5~deterministic~optimisation_report+restart_repro build_system=makefile type=ACCESS-CM  mom5@master~deterministic~optimisation_report+restart_repro build_system=makefile type=ACCESS-OM
mom5@master~deterministic~optimisation_report+restart_repro build_system=makefile type=ACCESS-CM
==> 3 installed packages
```
Everything works for me as I expect. Please test.
=> Use conditional values for the `type` variant

packages/um7/package.py
Closes #117.
Tested by successfully running
```
spack install um7@access-esm1.5^openmpi@4.0.2%intel@19.0.5.281 arch=linux-rocky8-x86_64
```
=> Add version access-esm1.5 to um7

packages/access-esm1p5/package.py
* Passing type="run" to help with module autoloading as per: https://spack.readthedocs.io/en/v0.22.0/module_file_support.html#autoloading-and-hiding-dependencies
=> access-esm1p5: pass type to depends_on()

packages/access-om2-bgc/package.py
* Passing type="run" to help with module autoloading as per: https://spack.readthedocs.io/en/v0.22.0/module_file_support.html#autoloading-and-hiding-dependencies
=> access-om2-bgc: pass type to depends_on()

packages/access-om2/package.py
* Passing type="run" to help with module autoloading as per: https://spack.readthedocs.io/en/v0.22.0/module_file_support.html#autoloading-and-hiding-dependencies
=> access-om2: pass type to depends_on()

packages/um7/package.py
Closes #122 
The changes are extensive, but should not affect the default or `debug` use cases.
1. Remove the unused `"omp"` and `"netcdf"` variants.
2. Change version range for `depends_on("netcdf-fortran")` from `4.5.1:4.5.2` to just `4.5.2`.
3. Use `edit`, `build` and `install` phases.
- In the `edit` phase, create an FCM config file whose contents depend on `opt_value`.
- In the `build` phase, use FCM and the Intel compiler to build the executable.
- In the `install` phase, install the executable into the `prefix.bin` directory.
4. In `setup_build_environment`, use list comprehensions to define `oasis3_incs` and `incs`, and use a loop to prepend to `CPATH` for each included directory.
5. Prepend to `LIBRARY_PATH` only for `gcom4`, since that library is the only one that must be …
=> Make um7 Spack package more consistent with other ACCESS-NRI Spack packages

packages/nci-openmpi/package.py
* Fixes #65
* For details, refer to: https://github.com/spack/spack/issues/42700
=> nci-openmpi: remove explict setup_run_environment() call

packages/access-om3-nuopc/package.py
=> access-om3-nuopc: depend on esmf with -fp-model precise

packages/mom5/package.py
This PR adds `submodules = True` to the MOM5 SPD to facilitate building with the code changes in https://github.com/ACCESS-NRI/MOM5/pull/27
Closes #133
=> Add `submodules = True` to MOM5 SPD

packages/access-ram3/package.py
Create deployment SBD `access-ram3` for the `ACCESS-NRI/ACCESS-RAM3` repository. Depends solely on `um` package. 
In this PR: 
* Add `packages/access-ram3/package.py` with appropriate dependencies. 
References ACCESS-NRI/ACCESS-RAM3#1
=> Add `access-ram3` SBD with `UM` SPD

packages/access-esm1p5/package.py, packages/access-esm1p6/package.py, packages/mom5/package.py
This PR adds a new SBD for ACCESS-ESM1.6. At the moment, this is only differs from ACCESS-ESM1.5 in how MOM5 is built.
Closes #140
=> ACCESS-ESM1.6 SBD

packages/access-test/package.py
@atteggiani made a good point that ACCESS-OM2 takes too long to build for testing our Spack instance. That got me thinking whether a Test/QA fake model release would be useful for CI, CD, Spack, Docker and Gadi testing ...
@CodeGat: "I'm starting to think more and more that it'd be a great idea."
=> access-test: new SPD to test ACCESS-NRI infrastructure

packages/fiat/intel_warnings_v110.patch, packages/fiat/intel_warnings_v120.patch, packages/fiat/package.py
Closes #147 
This package is used by the `um` package to add `DR_HOOK` as per #148.
This package is based on the builtin package, with the following differences.
1. It uses the [ACCESS-NRI/fiat](https://github.com/ACCESS-NRI/fiat.git) repository.
2. It adds a `"um"` version that uses the [`"um"` branch of `ACCESS-NRI/fiat`](https://github.com/ACCESS-NRI/fiat/tree/um). This branch [adds a modified version of `DR_HOOK_DEFAULT` that allows a communicator to be specified](https://github.com/ACCESS-NRI/fiat/commit/77cc81c170a342a7e0056c9a9249708c66587d56).
3. It does not patch the `"um"` version.
4. It adds `"CMAKE_*_COMPILER"` defines to `cmake_args` so that CMake can find the `mpifc` compiler, etc. 
```
$ diff -U0 -w spack/var/spack/repos/builtin/packages/fiat/package.py …
```
=> Add package for fiat based on builtin but adding um as a version

packages/gcom4/package.py
Switch to https for git to avoid need for ssh key password. (Maybe there is a reason for this ?)
=> Update package.py for GCOM package

packages/gcom4/package.py
Closes #158 
I tested this change on Gadi as follows:
```
[pcl851@gadi-login-05 ACCESS-NRI]$ spack install gcom4@access-esm1.5%intel@19.0.3.199+mpi target=x86_64_v4
[+] /usr (external glibc-2.28-mqjolvbeskcnhz5chvtdshk4x4sfnycs)
==> openmpi@4.1.5 : has external module in ['openmpi/4.1.5']
[+] /apps/openmpi/4.1.5 (external openmpi-4.1.5-d2fnwga5ru5576ituxh2dnltp2e2qzea)
[+] /g/data/tm70/pcl851/src/ACCESS-NRI/release/linux-rocky8-x86_64_v4/intel-19.0.3.199/fcm-2021.05.0-q2lzrtveje4vtlljpthvpqhszkh3heen
==> Installing gcom4-access-esm1.5-lh6rlw5e6n4z3urwnobg3ncqmtjag3s5 [4/4]
==> No binary for gcom4-access-esm1.5-lh6rlw5e6n4z3urwnobg3ncqmtjag3s5 found: installing from source
==> Ran patch() for gcom4
==> gcom4: Executing phase: 'install'
==> gcom4: Successfully installed …
```
=> Revert the recent change to the gcom4 git clone address

packages/access-generic-tracers/package.py
SPDs `access-mocsy` and `access-fms` have been merged. This is the last SPD needed to add generic-tracers support to MOM.
=> access-generic-tracers: create an SPD for ACCESS-NRI's fork

packages/mom5/package.py
This is the last step in-order to add generic tracers support to ACCESS-NRI's Spack Package Recipes (SPR) in the `spack-packages` repository.
Please note, even when generic-tracers support has been merged into the main branch of `spack-packages`, it does not mean that the feature has been merged into the main/master branch of the model's source repository. The source code for the feature may still be in a development branch of the model's source repository. e.g. https://github.com/ACCESS-NRI/MOM5/tree/development
In the MOM5 SPR, this feature is disabled by default. The variant `access-gtracers` must be deliberately enabled.
=> mom5: add new dependencies access-fms & access-generic-tracers

packages/mom5/package.py
While debugging an issue, I found that the variable name `$SPACK_BUILD` confusing because we use Spack to build MOM5 regardless of whether that variable is set to true of false.
=> mom5: use a more accurate name for an environment variable

packages/mom5/package.py
* The name SPACK_GTRACERS_EXTERNAL is better than SPACK_FMS_EXTERNAL.
=> mom5: use environment variable name SPACK_GTRACERS_EXTERNAL

packages/issm/package.py
Add support for new [ISSM GitHub repo](https://github.com/ISSMteam/ISSM).
Closes #167
=> Migrate ISSM to GitHub repo

packages/um7/package.py
First step to resolve: https://github.com/ACCESS-NRI/spack-packages/issues/175
=> um7: add version "access-esm1.6" that uses branch dev-access-esm1.6

packages/access-esm1p6/package.py
This PR increases flexibility by allowing the user to make the following choices:
1) cice = {4,5} (only cice4 has been tested)
2) generic-tracers = {True,False} (tested)
3) um = {access-esm1.5,access-esm1.6} (tested)
Closes #175
=> access-esm1p6: add variant cice, generic-tracers and um

packages/cice5/package.py, packages/cice5/spack-build.sh
@Harshula
When I try to use this package, it builds the wrong executable
I run 
`spack install cice5@git.access-esm1.6=access-esm1.6%intel@19.0.3.199`
and it builds the executable for access-cm2 ?
From the spack-build-out.txt file, I can see that spack is sending the wrong arguments to spack-build.sh :
```
==> cice5: Executing phase: 'build'
==> [2024-11-29-11:34:55.729889] '/g/data/tm70/as2285/spack0.22/spack/var/spack/environments/esm1_5/cice5/bld/spack-build.sh' 'access-cm2' '360x300' '12x1' '12'
```
Any ideas ?
=> Spack package to add build options for CICE5 in esm1.6

packages/access-om2/package.py, packages/cice5/package.py, packages/libaccessom2/package.py, packages/mom5/package.py, packages/oasis3-mct/package.py
* Originally there was only one version in each SPR. It was used to build access-om2. However, now we have more versions like access-esm1.5. By renaming version "master" to "access-om2", it is clear that is the version used to build access-om2.
* Use the new maintainers() function.
=> access-om2 SPRs: change the name of the default version

packages/fre-nctools/package.py
This PR adds a package for [FRE-NCtools](https://github.com/NOAA-GFDL/FRE-NCtools). The initial implementation is taken and updated from [COSIMA/spack_packages](https://github.com/COSIMA/spack_packages/blob/main/packages/fre-nctools/package.py).
Closes #143
=> Add fre-nctools package

packages/mom5/package.py
ifx:
```
[om2] [gadi-login-05 spack-packages]$ spack find mom5
==> In environment om2
==> 1 root specs
[+] access-om2@access-om2
==> Installed packages
-- linux-rocky8-x86_64 / oneapi@2025.0.4 ------------------------
mom5@git.2025.03.001=access-om2
==> 1 installed package
```
ifort:
```
[root@763ade9cfb88 opt]# spack find mom5
-- linux-rocky8-x86_64 / intel@2021.10.0 ------------------------
mom5@git.2025.03.001=access-om2
==> 1 installed package
```
=> mom5: add oneapi 2025 compiler support

packages/access-test-model/package.py
Add package recipe for test stub model component
Closes #205
=> Add package recipe for ACCESS-TEST-model

packages/gcom4/package.py
The source repo has already been updated with the oneAPI specific config files in a [separate PR](https://github.com/ACCESS-NRI/GCOM4/pull/6)
I tested with `spack -d install gcom4 %oneapi` and the install was successful with the fix (previously such attempts would crash with [this error](https://github.com/ACCESS-NRI/spack-packages/issues/193#issuecomment-2699325500)). 
```sh
<snip>
==> [2025-03-05-11:25:38.654150]        WRITE: gcom4@access-esm1.5%oneapi@2025.0.4+mpi build_system=generic arch=linux-rocky8-x86_64_v4/3zdxxya [/g/data/tm70/ms2335/spack/0.22/release/modules/linux-rocky8-x86_64_v4/gcom4/access-esm1.5-3zdxxya]
==> [2025-03-05-11:25:39.459366]        EXCLUDED_AS_IMPLICIT : glibc@2.28%oneapi@2025.0.4 build_system=autotools arch=linux-rocky8-x86_64_v4/gkllvhl
==> …
```
=> Added the fix to pickup the oneAPI specific config file for gcom4

packages/cice4/package.py, packages/mom5/package.py, packages/oasis3-mct/package.py, packages/um7/package.py
* The versions do not need to be hardcoded in the SPRs because we define the required versions 
in the `spack.yaml` Spack environment file.
* Removing hdf5 because it is a dependency of netcdf-c, not oasis3-mct.
=> ACCESS-ESM1.5 & ACCESS-ESM1.6: remove versions from dependencies

packages/access-om2/package.py
It's better to be consistent across all the SBRs and use `latest`.
=> access-om2: change the version back to latest

packages/issm/package.py
hash key is incorrect in the original SPR, see #220 , this is fixed now.
And there are known build conflicts associated with compiling iSSM using `gcc14` or newer, see #172 and #167, a simple fix to this is with Spack's `conflict()` directive, see [Conflicts & Requirements](https://spack.readthedocs.io/en/latest/packaging_guide.html#conflicts-and-requirements), stopping it from installing with `gcc` versions ">=14"
=> fixed sha256 key and added conflicts directive for building with gcc14 or newer

packages/issm/package.py
Addressing #222, develop version takes from main branch so `spack install issm@develop %gcc@13` now works as expected.
=> made develop version take tarball from main branch

packages/access-issm/package.py
Closes #217
Requires #184 
The ACCESS-NRI/ACCESS-ISSM model deployment repository requires an overarching `access-issm` bundle. 
* Added `access-issm` bundle, which depends on `issm`
=> Add `access-issm` bundle

packages/issm/package.py
see #184  
enable building of Spack issm package installation with wrappers - this allows matlab/python dependencies to be installed; so that Spack can be used to compile issm with pre- and post- processing features, either on a local machine or remote cluster.
=> enable building of spack issm installation with wrappers

packages/issm/package.py
remove `examples/` from `self.stage.source_path` #228, just keep standard serialised installation and build.
=> remove examples directory from ISSM's SPR

packages/access-esm1p5/package.py, packages/access-esm1p6/package.py, packages/access-om2-bgc/package.py, packages/mom5/package.py
=> mom5: remove access-gtracers and type variants

packages/access-fms/package.py
This is needed to preserve answers with ACCESS releases using MOM5 internal FMS - see [here](https://github.com/ACCESS-NRI/access-om2-configs/pull/191#issuecomment-2857276987).
=> access-fms: set variant gfs_phys default to False

packages/access-cice/package.py, packages/access-mom6/package.py, packages/access-ww3/package.py, packages/access3-share/package.py, packages/access3/package.py
* The default flag_handler is inject_flags. This method is opaque and verifying whether the flags were applied is difficult.
* Setting the flag_handler to build_system_flags should result in the flags appearing in the package's build logs.
=> access-om3 SPRs: use build_system_flags as the flag handler

packages/access-fms/package.py, packages/access-generic-tracers/package.py, packages/access-test-component/package.py, packages/cable/package.py, packages/datetime-fortran/package.py, packages/fiat/package.py, packages/fortranxml/package.py, packages/fre-nctools/package.py, packages/issm/package.py, packages/libaccessom2/package.py
* The default flag_handler is inject_flags. This method is opaque
and verifying whether the flags were applied is difficult.
* Setting the flag_handler to build_system_flags should result in the
flags appearing in the package's CMake build logs.
=> Autotools & CMake SPRs: use build_system_flags as the flag handler

packages/access-generic-tracers/package.py, packages/access-mom6/package.py
This PR adds `access-generic-tracers` as a dependency of `access-mom6`. It also adds a variant to the `access-generic-tracers` SPR to allow switching between depending on `access-fms` or `fms`. This defaults to `access-fms` for backwards compatibility.
Depends on:
- https://github.com/ACCESS-NRI/MOM6/pull/10
=> Add access-generic-tracers as a dependency of access-mom6

packages/access-cice/package.py, packages/access-generic-tracers/package.py, packages/access-mom6/package.py, packages/access-ww3/package.py, packages/access3-share/package.py, packages/access3/package.py
This PR sets the minimum FMS version in the access-generic-tracers package to 2025.02. This to include the export of FindNetCDF.cmake in the FMS cmake install dir. Thanks to @anton-seaice for catching this [here](https://github.com/ACCESS-NRI/spack-packages/pull/241#discussion_r2090350755).
ADDED:
In addition, this PR 
- adds versions to the `access-cice`, `access-mom6`, `access-ww3`, `access3-share` and `access3` SPRs
- specifies min versions of `access-cice`, `access-mom6`, `access-ww3` in the `access3` SPR
`access-generic-tracers` and `access-mocsy` are still in development. Versions will be added in a subsequent PR.
=> access-om3 main dependencies: add versions and specify min versions

packages/access-om2-bgc/package.py, packages/mom5/package.py
This PR updates the mom5 SPR for the [new CMake build system](https://github.com/ACCESS-NRI/MOM5/pull/39).
~Currently I have completely dropped support for the `access-esm1.5` version. We need to discuss how we want to handle this version since it is built from a different branch and is not built with CMake.~ UPDATE: no longer true. This SPR now supports two build systems:
Makefile build supporting:
- access-esm1.5
- access-om2
-  legacy-access-om2-bgc
CMake build supporting:
- mom_solo
- mom_sis
- access-om2
- legacy-access-om2-bgc
- access-esm1.6
Build will default to CMake where possible
=> Update mom5 SPR for new CMake build system

packages/issm/package.py
This PR lets the `+ad` (Automatic Differentiation) flavour of `issm` build and run out-of-the-box:
- Removes hidden PETSc dependency in sea-level sub-modules (`Love`), which broke the compile with `fatal error: petscblaslapack.h: No such file or directory.`
- Enables `--enable-tape-alloc` (upstream-recommended for CoDiPack performance / stability).
- Supplies an explicit `BLAS/LAPACK` path so the AD variant links cleanly on clusters that don’t inject it.
- Adds an optional `-lgfortran` link flag for mixed C/Fortran toolchains that drop the runtime.
- No change for the default “classic” PETSc-backed build.
Testing:
- `spack install issm +ad +wrappers %gcc@13` now completes on Gadi (OpenMPI 4.1.5)
=> ISSM: make +ad variant self-contained (no PETSc, no Love, tape-alloc on)”

packages/gcom4/package.py, packages/um7/package.py
Currently, `um7` and `gcom4` packages use SSH-style `git` URLs. This is because they are private, and in `build-cd` are cloned via service user SSH key. 
SSH keys have the same access to organisations and repositories (private/public, read/write/admin) as the user that created them, and can't be made finer in scope. A better solution would be to use a fine-grained GitHub PAT, which can be reduced in scope as appropriate. 
In order to use fine-grained GitHub PATs (which are used over `https` rather than `ssh`) for these private repositories, we need to change the `git` URLs from the SSH-style to the https-style URLs. 
This will also allow `build-ci` to clone private repositories via fine-grained PAT rather than SSH Key. 
- Convert `gcom4` package to `https`-style `git` URL
- Convert `um7` …
=> Convert `um7` and `gcom4` to https git URLs

packages/cice4/package.py, packages/cice5/package.py
[Updated 2025/07/03]
* Injecting `-flto` via `ldflags` in the `spack.yaml` was unsuccessful.
* Variant `linker` renamed to `direct_ldflags`.
=> cice4 / cice5: add direct_ldflags variant

packages/fre-nctools/package.py
This PR modifies the `fre-nctools` SPR to use ACCESS-NRI's fork of https://github.com/NOAA-GFDL/FRE-NCtools.git. This is necessary because we are having trouble getting changes included upstream. I've also added the version `2024.05-1` which includes ACCESS-NRI changes on top of `2024.05`.
Closes #267
=> fre-nctools: use ACCESS-NRI fork

packages/ancoms-roms/package.py, packages/coastri-roms/package.py
[Updated: 2025/07/10]
*  Copy roms SPR from upstream: https://github.com/spack/spack-packages/blob/develop/repos/spack_repo/builtin/packages/roms/package.py
* Add a git URL to support `@git.<gitref>`.
- https://github.com/ACCESS-Community-Hub/roms
- Explicit versions() removed because they are available via the `roms` SPR.
* SPR name changed to avoid a name collision with the upstream ROMS package and it makes `spack list` output more obvious. The two SPRs reference two different git repositories.
* Drop type hints from commit 77af1964ca3f42470825210c87e860e4a14e5d78 (Add type hints to all setup_*environment functions (#49985)) that touches all SPRs because of error, `name 'EnvironmentModifications' is not defined`. We may want to apply a similar commit across our entire repository when …
=> Add SPR and SBR to build CoastRI maintained ROMS

packages/mppnccombine-fast/package.py
This PR adds a SPR for [mppnccombine-fast](https://github.com/ACCESS-NRI/mppnccombine-fast)
Closes #74
```
$ spack install mppnccombine-fast %intel@2021.10.0
```
installs successfully and tests pass:
```
$ spack load mppnccombine-fast
$ module load conda openmpi/5.0.5
$ cd <mppnccombine-fast/src/dir>
$ pytest
================================================= test session starts ==================================================
platform linux -- Python 3.11.11, pytest-8.3.5, pluggy-1.5.0
rootdir: /g/data/tm70/ds0092/model/dev/mppnccombine-fast/mppnccombine-fast
plugins: hypothesis-6.117.0, cov-6.0.0
collected 15 items
test_mppnccombine.py ...............                                                                             [100%]
================================================= 15 …
```
=> mppnccombine-fast: Add SPR

.github/build-ci/manifests/default.spack.yaml.j2
Closes #282 
jinja tried to interpolate the template statements in the comments and didn't like the wildcard. Removed jinja templating sigils.
=> Fix jinja error in default CI manifest

packages/um/model/vn13p5-rns/rose-app.conf
Closes #279 
Checked by running
```
$ spack install um@13.5%intel model=vn13p5-rns
```
with result
```
[+] /apps/cmake/3.24.2 (external cmake-3.24.2-3elediqlz54ar5f4jtiaoqmmmsctdtqw)
[+] /usr (external glibc-2.28-rmko4qyyetyn6neqs7tnuusqbllgwbnb)
==> openmpi@5.0.5 : has external module in ['openmpi/5.0.5']
[...]
==> No patches needed for um
==> um: Executing phase: 'build'
==> um: Executing phase: 'install'
==> um: Successfully installed um-13.5-mgbsek5ivx34zbgzdr3o4trh3mdgimrg
Stage: 5.76s.  Build: 22m 36.15s.  Install: 0.47s.  Post-install: 1.72s.  Total: 22m 45.58s
[+] /g/data/tm70/pcl851/src/ACCESS-NRI/release/linux-rocky8-x86_64_v4/intel-2021.10.0/um-13.5-mgbsek5ivx34zbgzdr3o4trh3mdgimrg
```
=> Add sources to UM vn13p5-rns config to match u-by395/nci_access_ram3

packages/access-generic-tracers/package.py
This PR updates versions in the `access-generic-tracers` SPR. Specifically:
- Add version 2025.07.000
- Rename "master" version to "main" (default branch was renamed some months ago). I'm pretty confident this wasn't be used anywhere.
- Add note to delete the "development" version once we're confident it's not being used anywhere.
=> access-generic-tracers: Update versions

packages/um/package.py
Quick fix heavily inspired by @penguian's gcom example.
Currently running on AM3, which is now the recon phase where it last fell over due to the missing `mpirun` command resulting from an absence of openmpi.
=> Added openmpi as explicit dependency

packages/access-mom6/package.py
2025.08.000 has been deprecated due to a bug, see https://github.com/ACCESS-NRI/MOM6/issues/26
=> access-mom6: add 2025.07.000; deprecate 2025.08.000

packages/access-generic-tracers/package.py
This PR adds `access-generic-tracers@2025.04.001`. `2025.04.001` is the same as the `2025.04.0` release tag, but with the CMake build system backported so that it can be built with the latest version of the SPR.
=> access-generic-tracers: add 2025.04.001

packages/oasis3-mct/package.py
* Remove static list of Fortran module files.
* Remove function __init__().
* Simplify install().
=> oasis3-mct: add upstream version()

.github/workflows/ci.yml
See https://github.com/ACCESS-NRI/spack-packages/actions/runs/17287571815/job/49067594258?pr=315#step:13:4154 (from PR https://github.com/ACCESS-NRI/spack-packages/pull/315)
`ACCESS-ESM*`-related private components can't be built in `spack-packages` without a token. This PR adds a `secrets.SPACK_INSTALL_COMMAND_PAT` and ingests that via the workflow input `secrets.spack-install-command-pat`. 
* Add `secrets.spack-install-command-pat`
=> Add ACCESS-ESM* token for spack-install-command-pat

packages/mom5/package.py, packages/oasis3-mct/package.py
This PR includes changes to allow us to switch to using `oasis3-mct` built from the `master` branch, rather than `access-esm1.5` branch, in ACCESS-ESM1.6.
A `version("stable", branch="master", preferred=True)` is introduced into the `oasis3-mct` SPR. Using this version in ACCESS-ESM1.6 does not change answers or performance (despite the associated change from [`-xCORE-AVX512` to `-axCORE-AVX2`](https://github.com/ACCESS-NRI/spack-packages/blob/f3d8c580af2898557c19c23fb0eb2260865f272a/packages/oasis3-mct/package.py#L223-L226)) - see [here](https://github.com/ACCESS-NRI/access-esm1.6-configs/pull/187#issuecomment-3226289134) and [here](https://github.com/ACCESS-NRI/access-esm1.6-configs/pull/187#issuecomment-3226651458).
=> Use oasis3-mct master branch in ACCESS-ESM1.6

packages/um7/package.py
Remove the `-V` flags from the `fcm build` config within the UM7 Spack package recipe.
[At lines 277-289 of the Spack compiler wrapper](https://github.com/ACCESS-NRI/spack/blob/99f79c7cf1c97c55f5d1920679a4d5bb998b5dc3/lib/spack/env/cc#L277) there is a test to see if there are any arguments that represent a version check. In this case, [at lines 367-369](https://github.com/ACCESS-NRI/spack/blob/99f79c7cf1c97c55f5d1920679a4d5bb998b5dc3/lib/spack/env/cc#L367) the wrapper just executes the compiler command without adding arguments from `$SPACK_FFLAGS`.
```
if [ -z "$mode" ] || [ "$mode" = ld ]; then
for arg in "$@"; do
case $arg in
-v|-V|--version|-dumpversion)
mode=vcheck
break
;;
esac
done
fi
[...]
if [ "$mode" = vcheck ]; then
exec "${command}" "$@"
fi
```
Because lines 182, 186 and 188 of …
=> Do not use -V in fflags: it fools the Spack compiler wrapper

.github/workflows/ci.yml
See run https://github.com/ACCESS-NRI/spack-packages/actions/runs/17404574596/job/49459311901?pr=317 (specifically, the incorrect `.github/build-ci/manifests/access-om3/gcc.spack.yaml.j2` for `access-ram3` - it should either be a `access-ram3` manifest or the default `.github/build-ci/manifests/gcc.spack.yaml.j2`). 
* `unset` the `manifest_paths` variable between loops, as the `[ -z "$manifest_paths" ]` was picking up the previous loop iterations value. Whoops!
=> `build-ci`: Fix incorrect manifest search

packages/access-cice/package.py, packages/access-fms/package.py, packages/access-generic-tracers/package.py, packages/access-mocsy/package.py, packages/access-mom6/package.py, packages/access-test-component/package.py, packages/access-ww3/package.py, packages/access3-share/package.py, packages/access3/package.py, packages/cable/package.py, packages/datetime-fortran/package.py, packages/fiat/package.py, packages/fortranxml/package.py, packages/fre-nctools/package.py, packages/issm/package.py, packages/libaccessom2/package.py
The issues seen with the CMake build system (https://github.com/ACCESS-NRI/spack-packages/issues/268) have demonstrated that reverting back to the default `flag_handler` results in a more predicable user experience.
Furthermore, since Spack upstream are planning to save the compiler wrapper output alongside the build logs (https://github.com/spack/spack/issues/50972), the original need to override the default `flag_handler` is less relevant.
The Spack compiler flag overrides, e.g. `-g -O1`, are overridden by CMake defaults, e.g. `-O3`:
```
[cc] /opt/release/linux-rocky8-x86_64/gcc-8.5.0/intel-oneapi-compilers-2023.2.4-hxxociow5cqbgxig7jtdtiwpg6tst7bs/compiler/2023.2.4/linux/bin/intel64/ifort -g -O1 -O3 -c /tmp/root/spack-stage/spack-stage-access-test-component-main-7esg4kddhcj3nogz6y4x7zoh …
```
=> Use default flag handler

packages/access-generic-tracers/package.py
A small PR to add the new 2025.09.000 version to the access-generic-tracers SPR
=> access-generic-tracers: Add version 2025.09.000

packages/access-cice/package.py, packages/access3/package.py
Closes #324 
This PR adds a `driver` variant to the `access-cice` spack package. This allows a custom relative path to be set for the [`CICE_DRIVER` option](https://github.com/ACCESS-NRI/CICE/blob/725ca300c65647dade425c6d037fe1d6d335e853/configuration/scripts/cmake/CMakeLists.txt#L35-L43) in the CICE CMake build.
It also adds a `MOM6-CICE6-UM13` build configuration to the `access3` package, which adds `gcom` as a dependency when active, as suggested [here](https://github.com/ACCESS-NRI/dev_coupling/issues/56#issuecomment-2840460649). If we decide to it this way, this build configuration will also need to be added to the [known configurations](https://github.com/ACCESS-NRI/access3-share/blob/e89f37b504eeebba8f951e90f88078a479216104/cmake/Access3BinInstall.cmake#L10) in the cmake build
=> Add options for building libraries for CM3
