ACCESS-NRI/spack-packages

packages/access-om3/package.py
Closes #11 
I did not update the copyright header. I had a quick look at the Spack repo, and as it seems no one bothers to do that.
=> Fixes several small issues with the ACCESS-OM3 package.

packages/mom5/package.py
=> mom5: parallelio is not a dependency

packages/mom5/package.py
Fixes https://github.com/ACCESS-NRI/spack_packages/issues/22
=> MOM5: Add version specific tarball URL specification

packages/cice5/package.py
* Print the generated config file to stdout.
* Close #14.
=> cice5: explicitly set the rpath of library dependencies

packages/cice5/package.py, packages/libaccessom2/package.py, packages/mom5/package.py, packages/oasis3-mct/package.py
I spoke with @penguian, these flags were not intended to be enabled by default.
=> Add optimisation_report variant

.github/workflows/py-checks.yml, .ruff.toml
Adding a workflow for python syntax checks on PR. 
Closes #38 !
=> Python PR checks

.github/workflows/py-checks.yml, .ruff.toml
Added ignored error codes, updated line length and added a check for changed files
=> Updated python check config

packages/access-om3/package.py
This now builds and install the OM3 executables and is aware of the different variants.
=> Proper implementation of ACCESS-OM3 SPD

packages/access-om3/package.py
There is a new dependency and there is a new option to install the libraries created during compilation of the models.
=> Update OM3 package to take into account recent changes

packages/mom5/package.py
Closes #78 
Change `+restart_repro` variant to default to `True`.
=> Change mom5 to +restart_repro default True

packages/access-om3-virtual/package.py
Closes #89 
References https://github.com/ACCESS-NRI/ACCESS-OM3/issues/3
=> Added `access-om3-virtual` bundle definition

packages/fortranxml/package.py
* url_for_versions() downloads: https://github.com/andreww/fox/tarball/4.1.2
* sha256sum: 1938725be45b8be5387a51fa0b25ee78ffee87ca8a497b82545ab870f33f8b88
=> fortranxml: correct the checksum

packages/access-esm1p5/package.py
Another component is ready for testing.
=> access-esm1p5: add dependency mom5@access-esm1.5

packages/cice4/package.py, packages/mom5/package.py, packages/oasis3-mct/package.py, packages/um7/package.py
Closes #120 
The executables `cice4`, `mom5` and `um7` executables in the following configuration reproduce the output of https://github.com/ACCESS-NRI/access-esm1.5-configs/tree/pre-industrial https://github.com/ACCESS-NRI/access-esm1.5-configs/blob/0f769ae4338005f8ed3c6ce6478e004842d4a598/config.yaml
```
spack find
-- linux-rocky8-x86_64_v4 / gcc@8.5.0 ---------------------------
bzip2@1.0.8  c-blosc@1.21.5  cmake@3.24.2  diffutils@3.9  gmake@4.3  hdf5@1.10.11  libaec@1.0.6  libiconv@1.17  lz4@1.9.4  netcdf-c@4.7.1  openmpi@4.0.2  pkgconf@1.9.5  snappy@1.1.10  zlib-ng@2.1.4  zstd@1.5.5
-- linux-rocky8-x86_64_v4 / intel@19.0.3.199 --------------------
cice4@access-esm1.5  dummygrib@1.0  fcm@2021.05.0  gcom4@access-esm1.5  gmake@4.4.1  mom5@access-esm1.5  netcdf-fortran@4.5.2 …
```
=> Reproduce pre-industrial output

packages/access-esm1p5/package.py
Closes #123 
This is for consistency with https://github.com/ACCESS-NRI/UM_v7/issues/7
=> Use um7@access-esm1.5 in access-esm1p5

packages/um7/package.py
Closes #137 
Testing `spack install` successfully resulted in the creation of an executable:
```
$ spack install um7@access-esm1.5%intel@19.0.3.199 arch=linux-rocky8-x86_64_v4
[+] /usr (external glibc-2.28-mqjolvbeskcnhz5chvtdshk4x4sfnycs)
==> openmpi@4.1.0 : has external module in ['openmpi/4.1.0']
[+] /apps/openmpi/4.1.0 (external openmpi-4.1.0-zu2hmm5cqosdadfxpckiaawc7iy3hv3k)
[+] /g/data/tm70/pcl851/src/ACCESS-NRI/release/linux-rocky8-x86_64_v4/intel-19.0.3.199/pkgconf-2.2.0-ugenh6g4dnhti4p6ktbkfku6pzlq5fkr
[+] /g/data/tm70/pcl851/src/ACCESS-NRI/release/linux-rocky8-x86_64_v4/intel-19.0.3.199/fcm-2021.05.0-q2lzrtveje4vtlljpthvpqhszkh3heen
[+] /g/data/tm70/pcl851/src/ACCESS-NRI/release/linux-rocky8-x86_64_v4/intel-19.0.3.199/zlib-ng-2.1.6-h45fvywj47wc4uwa37mfzkdsqrgcqxux
[+] …
```
=> Use ACCESS-NRI/UM7 for the um7 Spack package

packages/access-om2/package.py
=> access-om2: use the maintainer function

packages/um/package.py
Closes #148 
Add `DR_HOOK` as a recognized variant, using the [fiat](https://github.com/ACCESS-NRI/spack-packages/tree/main/packages/fiat) Spack package. Verified by running
```
spack install -vvv um@13.0 +DR_HOOK %intel@19.0.3.199 arch=linux-rocky8-x86_64_v4 model=vn13p0-rns
```
to produce executables in `/g/data/tm70/pcl851/src/ACCESS-NRI/release/linux-rocky8-x86_64_v4/intel-19.0.3.199/um-13.0-pkv2vimllbjyu2pnyn4sraxbnmjlr524` and then running the `u-dg768` suite from `/home/851/pcl851/roses/u-dg768` using these executables.
=> Add drhook to the um package

packages/cable/package.py
As discussed, PR to add the library variant to the stack build.
=> Added CABLE_LIBRARY variant.

README.md, packages/cice4/package.py, packages/cice5/package.py, packages/um/package.py, packages/um7/package.py
@VanuatuN reported the `git repo add` typo.
=> README.md: fix typos

packages/access-test-component/package.py, packages/access-test-model-component/package.py
=> Rename package to access-test-component

packages/access-test/package.py
Closes #191 
Required for https://github.com/ACCESS-NRI/ACCESS-TEST/issues/32
=> Switch to using the ACCESS-TEST-model component

packages/access-om2-bgc/package.py, packages/access-om3-nuopc/package.py, packages/access-om3/package.py, packages/access-ram3/package.py, packages/datetime-fortran/package.py, packages/fortranxml/package.py
* SBR: access-om2-bgc, access-om3-nuopc, access-om3, access-ram3
* SPR: datetime-fortran, fortranxml
=> Use the maintainers() function

packages/access-cice/package.py, packages/cice4/package.py, packages/cice5/package.py
=> set cice license

packages/access-mocsy/package.py
This PR adds support to the access-mocsy SPR for the CMake build system added in https://github.com/ACCESS-NRI/mocsy/pull/1.
Note, the `"master"` `version` is also removed, since neither the CMake nor existing Makefile build system support building the master branch.
=> access-mocsy: Add CMake build_system (default)

packages/access-cice/package.py, packages/access-mom6/package.py, packages/access-ww3/package.py, packages/access3-share/package.py, packages/access3/package.py
This adds "stable" and hashes for numbered versions of om3 packages per #285
=> Add "stable" version as spack "infinity" version

packages/access-cice/package.py, packages/access-generic-tracers/package.py, packages/access-mocsy/package.py, packages/access-mom6/package.py, packages/access-ww3/package.py, packages/access3-share/package.py, packages/access3/package.py
This change adds new versions of the model components for access-om3
=> Set model component versions for om3 2025.08.000

packages/access3-share/package.py, packages/access3/package.py
=> force same versions in access3 and access3-share
